# Generated by Django 3.0.6 on 2020-05-31 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200531_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
