# Generated by Django 3.0.6 on 2020-06-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0003_auto_20200601_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='shared_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
